    source 'https://rubygems.org' 
 
        ruby '2.5.1' 

        gem 'rubocop', '~> 0.57.2'  

        gem 'pry' 

        gem 'nokogiri' 

        gem 'watir' 

        gem 'json' 

        gem 'csv' 

        gem 'google_drive' 

        gem 'launchy'

	gem 'dotenv'

	gem 'rspec'
